version: "3.9"

services:
  db:
    container_name: portal_hero_db
    image: postgres:17.2-alpine3.21
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=portal_hero
      - POSTGRES_USER=ph_user
      - POSTGRES_PASSWORD=ph_password
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 10